apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ubi8-python
  spec:
    dockerImageRepository: registry.redhat.io/ubi8/python-36
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: mesh-demo-base
  spec:
    lookupPolicy:
      local: true
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: mesh-demo-base
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: mesh-demo-base:latest
    source:
      type: Git
      git: 
        uri: "https://github.com/cnuland/service-mesh-poc"
        ref: "master"
      contextDir: "base/"
      secrets:
        - secret:
            name: etc-pki-entitlement
          destinationDir: etc-pki-entitlement
    strategy:
      dockerStrategy:
        buildArgs:
        - name: OCP_VERSION
          value: "4.3"
        from:
          kind: ImageStreamTag
          name: ubi8-python:latest
      type: Docker
    postCommit: {}
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
